MiraGeoscience/geoapps-utils

geoapps_utils/__init__.py, pyproject.toml
**GEOPY-1231 - Release: geoapps-utils-0.2.0**
=> GEOPY-1231

pyproject.toml
**GEOPY-1154 - add PyPI classifiers for geoapps-utils**
=> GEOPY-1154

geoapps_utils/__init__.py, pyproject.toml
**GEOPY-1242 - Release geoapps-utils 0.2.0a2**
=> GEOPY-1242

.pre-commit-config.yaml
**GEOPY-1228 - Implement BaseData class with pydantic**
=> GEOPY-1228

geoapps_utils/locations.py, tests/locations_test.py
**GEOPY-1267 - get_locations on GridObject references to vertices**
=> GEOPY-1267

geoapps_utils/application/dash_application.py
**GEOPY-1054 - Peak finder mouse offset**
=> GEOPY-1054

.github/workflows/pytest-windows.yaml
**GEOPY-1155 - configure codecov and codeclimate for geoapps-utils**
=> Geopy 1155 geoapps utils codecov

geoapps_utils/application/dash_application.py
**GEOPY-1326 - Remove dcc.Store from peak finder**
=> GEOPY-1326

.pre-commit-config.yaml, geoapps_utils/driver/data.py, geoapps_utils/locations.py, geoapps_utils/numerical.py, tests/dataclass_test.py, tests/numerical_test.py
**GEOPY-1348 - Add azimuth based filter option on trend lines**
=> GEOPY-1348

geoapps_utils/__init__.py, pyproject.toml
=> DEVOPS-259 set version

.pre-commit-config.yaml, devtools/setup-conda-base.bat, devtools/setup-dev.bat, pyproject.toml
**GEOPY-1472 - prepare distribution**
=> GEOPY-1472: prepare distribution

environments/py-3.10-linux-64-dev.conda.lock.yml, environments/py-3.10-linux-64.conda.lock.yml, environments/py-3.10-win-64-dev.conda.lock.yml, environments/py-3.10-win-64.conda.lock.yml, geoapps_utils/__init__.py, py-3.10.conda-lock.yml, pyproject.toml
**GEOPY-1472 - prepare distribution**
Allow Conda  to choose a version that exists in Conda index
with a higher version than the one resolved by Poetry in PyPI.
At the end the version picked by Conda is the one used.
=> GEOPY-1472: resolve version conflict between Conda and Poetry for PySide

geoapps_utils/application/dash_application.py
**GEOPY-1507 - dash app references a CSS on the web**
=> GEOPY-1507: dash app references a CSS on the web

geoapps_utils/locations.py, tests/locations_test.py
**GEOPY-1567 - Clip surfaces by ndv of data values**
…eg_drivers
=> GEOPY-1567: Clip surfaces by ndv of data values

geoapps_utils-assets/__init__.py, geoapps_utils/driver/data.py, geoapps_utils/driver/driver.py, geoapps_utils/driver/params.py, tests/dataclass_test.py, tests/driver_test.py
**GEOPY-1688 - allow baseDriver to accept BaseData**
Accept BaseData as params
=> GEOPY-1688: allow baseDriver to accept BaseData

environments/py-3.10-linux-64-dev.conda.lock.yml, environments/py-3.10-linux-64.conda.lock.yml, environments/py-3.10-win-64-dev.conda.lock.yml, environments/py-3.10-win-64.conda.lock.yml, environments/py-3.11-linux-64-dev.conda.lock.yml, environments/py-3.11-linux-64.conda.lock.yml, environments/py-3.11-win-64-dev.conda.lock.yml, environments/py-3.11-win-64.conda.lock.yml, environments/py-3.12-linux-64-dev.conda.lock.yml, environments/py-3.12-linux-64.conda.lock.yml, environments/py-3.12-win-64-dev.conda.lock.yml, environments/py-3.12-win-64.conda.lock.yml, geoapps_utils-assets/uijson/base.ui.json, geoapps_utils/__init__.py, geoapps_utils/driver/driver.py, geoapps_utils/driver/params.py, py-3.10.conda-lock.yml, py-3.11.conda-lock.yml, py-3.12.conda-lock.yml
**GEOPY-1774 - Re-order the inversion inputs following users comments**
=> GEOPY-1774: Re-order the inversion inputs following users comments

.codeclimate.yml, geoapps_utils/__init__.py, geoapps_utils/utils/numerical.py, pylintrc
**DEVOPS-515 - release branches to prepare distrib for Analyst 4.5**
=> DEVOPS-515: fix linter errors

geoapps_utils/utils/importing.py, geoapps_utils/utils/reference.py, tests/dataclass_test.py, tests/reference_test.py
add petro-lingo function in utils
And a pydantic BaseClass for GroupValue groups
=> GEOPY-1844: transfer utils fonctions from petro-lingo to geoapps-utils

environments/py-3.10-linux-64-dev.conda.lock.yml, environments/py-3.10-linux-64.conda.lock.yml, environments/py-3.10-win-64-dev.conda.lock.yml, environments/py-3.10-win-64.conda.lock.yml, environments/py-3.11-linux-64-dev.conda.lock.yml, environments/py-3.11-linux-64.conda.lock.yml, environments/py-3.11-win-64-dev.conda.lock.yml, environments/py-3.11-win-64.conda.lock.yml, environments/py-3.12-linux-64-dev.conda.lock.yml, environments/py-3.12-linux-64.conda.lock.yml, environments/py-3.12-win-64-dev.conda.lock.yml, environments/py-3.12-win-64.conda.lock.yml, py-3.10.conda-lock.yml, py-3.11.conda-lock.yml, py-3.12.conda-lock.yml
**GEOPY-1918 - Don't load workspace_geoh5 by default.**
=> GEOPY-1918: Don't load workspace_geoh5 by default.

geoapps_utils/driver/data.py
**GEOPY-1842 - Refactor Params class with BaseData**
…cting options in serialize method
=> GEOPY-1842

geoapps_utils/driver/driver.py
**GEOPY-2020 - run the Geoapps error context of geoapps utils for data preparation too.**
add the driver creation in the GeoApps Error context
=> GEOPY-2020: run the Geoapps error context of geoapps utils for data preparation too.

geoapps_utils/driver/driver.py
**GEOPY-1929 - Clean up double warning lines**
=> GEOPY-1929: Clean up double warning lines

geoapps_utils/driver/driver.py
**GEOPY-2027 - geoapps-utils return code is 0 upon failure**
raise an error with sys.exit(1) in geoapps-utils as asked
=> GEOPY-2027: geoapps-utils return code is 0 upon failure

environments/py-3.10-linux-64-dev.conda.lock.yml, environments/py-3.10-linux-64.conda.lock.yml, environments/py-3.10-win-64-dev.conda.lock.yml, environments/py-3.10-win-64.conda.lock.yml, environments/py-3.11-linux-64-dev.conda.lock.yml, environments/py-3.11-linux-64.conda.lock.yml, environments/py-3.11-win-64-dev.conda.lock.yml, environments/py-3.11-win-64.conda.lock.yml, environments/py-3.12-linux-64-dev.conda.lock.yml, environments/py-3.12-linux-64.conda.lock.yml, environments/py-3.12-win-64-dev.conda.lock.yml, environments/py-3.12-win-64.conda.lock.yml, geoapps_utils/driver/data.py, py-3.10.conda-lock.yml, py-3.11.conda-lock.yml, py-3.12.conda-lock.yml, tests/dataclass_test.py
**GEOPY-2068 - Clean up pydantic warnings**
=> GEOPY-2068: Clean up pydantic warnings

.github/workflows/python_deploy_prod.yml, geoapps_utils/driver/data.py
**GEOPY-2234 - Use aliases for old parameter names in legacy uijsons**
=> GEOPY-2234: Use aliases for old parameter names in legacy uijsons

geoapps_utils/base.py, geoapps_utils/run.py, tests/driver_test.py
**GEOPY-2188 - single entry point to run any application**
=> GEOPY-2188: single entry point to run any application

geoapps_utils/base.py, tests/dataclass_test.py
**GEOPY-2329 - Make pydantic validator issues returns clean GeoAppsError option**
catch pydantic error as nice errors
=> GEOPY-2329: Make pydantic validator issues returns clean GeoAppsError option

environments/py-3.10-linux-64-dev.conda.lock.yml, environments/py-3.10-linux-64.conda.lock.yml, environments/py-3.10-win-64-dev.conda.lock.yml, environments/py-3.10-win-64.conda.lock.yml, environments/py-3.11-linux-64-dev.conda.lock.yml, environments/py-3.11-linux-64.conda.lock.yml, environments/py-3.11-win-64-dev.conda.lock.yml, environments/py-3.11-win-64.conda.lock.yml, environments/py-3.12-linux-64-dev.conda.lock.yml, environments/py-3.12-linux-64.conda.lock.yml, environments/py-3.12-win-64-dev.conda.lock.yml, environments/py-3.12-win-64.conda.lock.yml, geoapps_utils/base.py, py-3.10.conda-lock.yml, py-3.11.conda-lock.yml, py-3.12.conda-lock.yml
**GEOPY-2440 - add a copy group+object base in inputfile as it exists uin uijhson group**
=> GEOPY-2440: add a copy group+object base in inputfile as it exists uin uijhson group

geoapps_utils/base.py, geoapps_utils/driver/params.py, pyproject.toml
**GEOPY-2440 - add a copy group+object base in inputfile as it exists uin uijhson group**
=> GEOPY-2440: b
